#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AndroidStatusShare.Resource", IsApplication=true)]

namespace AndroidStatusShare
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040003
			public const int actionbar_background_bottom = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int actionbar_background_end = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int actionbar_background_start = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int actionbar_background_top = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int actionbar_text = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int background = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int background_signup = 2130968577;
			
			// aapt resource value: 0x7f040012
			public const int ebony = 2130968594;
			
			// aapt resource value: 0x7f04000c
			public const int edit_text_background = 2130968588;
			
			// aapt resource value: 0x7f04000f
			public const int edit_text_cursor = 2130968591;
			
			// aapt resource value: 0x7f04000d
			public const int edit_text_inner = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int edit_text_outer = 2130968590;
			
			// aapt resource value: 0x7f040011
			public const int ghost_white = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int kinvey_orange = 2130968592;
			
			// aapt resource value: 0x7f040008
			public const int sign_up_text = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int sign_up_text_link = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int splash_text = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int text = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int text_dark = 2130968586;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actionbar_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int camera = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int edit_text_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int edit_text_cursor = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int grid_blank = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_menu_refresh = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_menu_start_conversation = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_title_share_default = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon_small = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int kinvey_button = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int kinvey_button_text_color = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int @lock = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int rounded_layout = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int spinner = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int spinner_outer = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int splash_land = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int splash_port = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int unlock = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070013
			public const int auther_updates_title = 2131165203;
			
			// aapt resource value: 0x7f070015
			public const int author_list_loading = 2131165205;
			
			// aapt resource value: 0x7f070012
			public const int author_name = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int author_updateList = 2131165204;
			
			// aapt resource value: 0x7f070011
			public const int avatar = 2131165201;
			
			// aapt resource value: 0x7f070002
			public const int comment_text = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int comment_title = 2131165185;
			
			// aapt resource value: 0x7f070010
			public const int empty_list = 2131165200;
			
			// aapt resource value: 0x7f070004
			public const int et_login = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int et_password = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int fragmentBox = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int login = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int login_label_password = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int login_label_username = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int login_register = 2131165192;
			
			// aapt resource value: 0x7f070023
			public const int menu_refresh = 2131165219;
			
			// aapt resource value: 0x7f070021
			public const int menu_send_post = 2131165217;
			
			// aapt resource value: 0x7f070024
			public const int menu_sign_out = 2131165220;
			
			// aapt resource value: 0x7f070022
			public const int menu_status_post = 2131165218;
			
			// aapt resource value: 0x7f070019
			public const int preview = 2131165209;
			
			// aapt resource value: 0x7f07001b
			public const int row_comment_author = 2131165211;
			
			// aapt resource value: 0x7f07001a
			public const int row_comment_text = 2131165210;
			
			// aapt resource value: 0x7f07001c
			public const int row_comment_time = 2131165212;
			
			// aapt resource value: 0x7f07001f
			public const int row_update_author = 2131165215;
			
			// aapt resource value: 0x7f07001d
			public const int row_update_image = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int row_update_text = 2131165214;
			
			// aapt resource value: 0x7f070020
			public const int row_update_time = 2131165216;
			
			// aapt resource value: 0x7f070018
			public const int share_attach_title = 2131165208;
			
			// aapt resource value: 0x7f070016
			public const int share_title = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int update = 2131165207;
			
			// aapt resource value: 0x7f07000e
			public const int updateList = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int updateProgress = 2131165199;
			
			// aapt resource value: 0x7f07000a
			public const int update_author = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int update_comment_list = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int update_image = 2131165195;
			
			// aapt resource value: 0x7f070009
			public const int update_text = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int updatesMain = 2131165197;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_fragment_holder = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_edit_comment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fragment_update_details = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int fragment_updates_list = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int fragment_view_author = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int fragment_write_update = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int row_comment = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int row_update = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int menu_editshare = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int menu_sharelist = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050013
			public const int about_msg = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int about_ok = 2131034132;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int author_update_list_title = 2131034119;
			
			// aapt resource value: 0x7f050011
			public const int confirm_password = 2131034129;
			
			// aapt resource value: 0x7f050008
			public const int desc_avatar = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int desc_picture = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int description_about = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int description_avatar = 2131034118;
			
			// aapt resource value: 0x7f050016
			public const int description_preview = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int description_refresh = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int description_send = 2131034135;
			
			// aapt resource value: 0x7f050004
			public const int description_sign_out = 2131034116;
			
			// aapt resource value: 0x7f050010
			public const int description_sign_up = 2131034128;
			
			// aapt resource value: 0x7f05000c
			public const int description_status_post = 2131034124;
			
			// aapt resource value: 0x7f050018
			public const int hint_update = 2131034136;
			
			// aapt resource value: 0x7f05000b
			public const int latest_updates = 2131034123;
			
			// aapt resource value: 0x7f050002
			public const int login_password = 2131034114;
			
			// aapt resource value: 0x7f05000d
			public const int login_text = 2131034125;
			
			// aapt resource value: 0x7f050001
			public const int login_username = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int post_update = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int register_text = 2131034115;
			
			// aapt resource value: 0x7f05000f
			public const int sign_up = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int signup_link = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int title_about = 2131034130;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
