#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("UnitTestFrameworkAndroid.Resource", IsApplication=true)]

namespace UnitTestFrameworkAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::UnitTestFrameworkAndroid.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::UnitTestFrameworkAndroid.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::UnitTestFrameworkAndroid.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::UnitTestFrameworkAndroid.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::UnitTestFrameworkAndroid.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::UnitTestFrameworkAndroid.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::UnitTestFrameworkAndroid.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest = global::UnitTestFrameworkAndroid.Resource.Id.ResultRunSingleMethodTest;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::UnitTestFrameworkAndroid.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::UnitTestFrameworkAndroid.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::UnitTestFrameworkAndroid.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::UnitTestFrameworkAndroid.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::UnitTestFrameworkAndroid.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::UnitTestFrameworkAndroid.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::UnitTestFrameworkAndroid.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::UnitTestFrameworkAndroid.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::UnitTestFrameworkAndroid.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::UnitTestFrameworkAndroid.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::UnitTestFrameworkAndroid.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::UnitTestFrameworkAndroid.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::UnitTestFrameworkAndroid.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::UnitTestFrameworkAndroid.Resource.Layout.test_suite;
			global::KinveyXamarinAndroid.Resource.Attribute.circleCrop = global::UnitTestFrameworkAndroid.Resource.Attribute.circleCrop;
			global::KinveyXamarinAndroid.Resource.Attribute.imageAspectRatio = global::UnitTestFrameworkAndroid.Resource.Attribute.imageAspectRatio;
			global::KinveyXamarinAndroid.Resource.Attribute.imageAspectRatioAdjust = global::UnitTestFrameworkAndroid.Resource.Attribute.imageAspectRatioAdjust;
			global::KinveyXamarinAndroid.Resource.Color.common_action_bar_splitter = global::UnitTestFrameworkAndroid.Resource.Color.common_action_bar_splitter;
			global::KinveyXamarinAndroid.Resource.Color.common_signin_btn_dark_text_default = global::UnitTestFrameworkAndroid.Resource.Color.common_signin_btn_dark_text_default;
			global::KinveyXamarinAndroid.Resource.Color.common_signin_btn_dark_text_disabled = global::UnitTestFrameworkAndroid.Resource.Color.common_signin_btn_dark_text_disabled;
			global::KinveyXamarinAndroid.Resource.Color.common_signin_btn_dark_text_focused = global::UnitTestFrameworkAndroid.Resource.Color.common_signin_btn_dark_text_focused;
			global::KinveyXamarinAndroid.Resource.Color.common_signin_btn_dark_text_pressed = global::UnitTestFrameworkAndroid.Resource.Color.common_signin_btn_dark_text_pressed;
			global::KinveyXamarinAndroid.Resource.Color.common_signin_btn_default_background = global::UnitTestFrameworkAndroid.Resource.Color.common_signin_btn_default_background;
			global::KinveyXamarinAndroid.Resource.Color.common_signin_btn_light_text_default = global::UnitTestFrameworkAndroid.Resource.Color.common_signin_btn_light_text_default;
			global::KinveyXamarinAndroid.Resource.Color.common_signin_btn_light_text_disabled = global::UnitTestFrameworkAndroid.Resource.Color.common_signin_btn_light_text_disabled;
			global::KinveyXamarinAndroid.Resource.Color.common_signin_btn_light_text_focused = global::UnitTestFrameworkAndroid.Resource.Color.common_signin_btn_light_text_focused;
			global::KinveyXamarinAndroid.Resource.Color.common_signin_btn_light_text_pressed = global::UnitTestFrameworkAndroid.Resource.Color.common_signin_btn_light_text_pressed;
			global::KinveyXamarinAndroid.Resource.Color.common_signin_btn_text_dark = global::UnitTestFrameworkAndroid.Resource.Color.common_signin_btn_text_dark;
			global::KinveyXamarinAndroid.Resource.Color.common_signin_btn_text_light = global::UnitTestFrameworkAndroid.Resource.Color.common_signin_btn_text_light;
			global::KinveyXamarinAndroid.Resource.Drawable.common_full_open_on_phone = global::UnitTestFrameworkAndroid.Resource.Drawable.common_full_open_on_phone;
			global::KinveyXamarinAndroid.Resource.Drawable.common_ic_googleplayservices = global::UnitTestFrameworkAndroid.Resource.Drawable.common_ic_googleplayservices;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_icon_dark = global::UnitTestFrameworkAndroid.Resource.Drawable.common_signin_btn_icon_dark;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_icon_disabled_dark = global::UnitTestFrameworkAndroid.Resource.Drawable.common_signin_btn_icon_disabled_dark;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_icon_disabled_focus_dark = global::UnitTestFrameworkAndroid.Resource.Drawable.common_signin_btn_icon_disabled_focus_dark;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_icon_disabled_focus_light = global::UnitTestFrameworkAndroid.Resource.Drawable.common_signin_btn_icon_disabled_focus_light;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_icon_disabled_light = global::UnitTestFrameworkAndroid.Resource.Drawable.common_signin_btn_icon_disabled_light;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_icon_focus_dark = global::UnitTestFrameworkAndroid.Resource.Drawable.common_signin_btn_icon_focus_dark;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_icon_focus_light = global::UnitTestFrameworkAndroid.Resource.Drawable.common_signin_btn_icon_focus_light;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_icon_light = global::UnitTestFrameworkAndroid.Resource.Drawable.common_signin_btn_icon_light;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_icon_normal_dark = global::UnitTestFrameworkAndroid.Resource.Drawable.common_signin_btn_icon_normal_dark;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_icon_normal_light = global::UnitTestFrameworkAndroid.Resource.Drawable.common_signin_btn_icon_normal_light;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_icon_pressed_dark = global::UnitTestFrameworkAndroid.Resource.Drawable.common_signin_btn_icon_pressed_dark;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_icon_pressed_light = global::UnitTestFrameworkAndroid.Resource.Drawable.common_signin_btn_icon_pressed_light;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_text_dark = global::UnitTestFrameworkAndroid.Resource.Drawable.common_signin_btn_text_dark;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_text_disabled_dark = global::UnitTestFrameworkAndroid.Resource.Drawable.common_signin_btn_text_disabled_dark;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_text_disabled_focus_dark = global::UnitTestFrameworkAndroid.Resource.Drawable.common_signin_btn_text_disabled_focus_dark;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_text_disabled_focus_light = global::UnitTestFrameworkAndroid.Resource.Drawable.common_signin_btn_text_disabled_focus_light;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_text_disabled_light = global::UnitTestFrameworkAndroid.Resource.Drawable.common_signin_btn_text_disabled_light;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_text_focus_dark = global::UnitTestFrameworkAndroid.Resource.Drawable.common_signin_btn_text_focus_dark;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_text_focus_light = global::UnitTestFrameworkAndroid.Resource.Drawable.common_signin_btn_text_focus_light;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_text_light = global::UnitTestFrameworkAndroid.Resource.Drawable.common_signin_btn_text_light;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_text_normal_dark = global::UnitTestFrameworkAndroid.Resource.Drawable.common_signin_btn_text_normal_dark;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_text_normal_light = global::UnitTestFrameworkAndroid.Resource.Drawable.common_signin_btn_text_normal_light;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_text_pressed_dark = global::UnitTestFrameworkAndroid.Resource.Drawable.common_signin_btn_text_pressed_dark;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_text_pressed_light = global::UnitTestFrameworkAndroid.Resource.Drawable.common_signin_btn_text_pressed_light;
			global::KinveyXamarinAndroid.Resource.Id.adjust_height = global::UnitTestFrameworkAndroid.Resource.Id.adjust_height;
			global::KinveyXamarinAndroid.Resource.Id.adjust_width = global::UnitTestFrameworkAndroid.Resource.Id.adjust_width;
			global::KinveyXamarinAndroid.Resource.Id.none = global::UnitTestFrameworkAndroid.Resource.Id.none;
			global::KinveyXamarinAndroid.Resource.Integer.google_play_services_version = global::UnitTestFrameworkAndroid.Resource.Integer.google_play_services_version;
			global::KinveyXamarinAndroid.Resource.String.auth_google_play_services_client_facebook_display_name = global::UnitTestFrameworkAndroid.Resource.String.auth_google_play_services_client_facebook_display_name;
			global::KinveyXamarinAndroid.Resource.String.auth_google_play_services_client_google_display_name = global::UnitTestFrameworkAndroid.Resource.String.auth_google_play_services_client_google_display_name;
			global::KinveyXamarinAndroid.Resource.String.common_android_wear_notification_needs_update_text = global::UnitTestFrameworkAndroid.Resource.String.common_android_wear_notification_needs_update_text;
			global::KinveyXamarinAndroid.Resource.String.common_android_wear_update_text = global::UnitTestFrameworkAndroid.Resource.String.common_android_wear_update_text;
			global::KinveyXamarinAndroid.Resource.String.common_android_wear_update_title = global::UnitTestFrameworkAndroid.Resource.String.common_android_wear_update_title;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_api_unavailable_text = global::UnitTestFrameworkAndroid.Resource.String.common_google_play_services_api_unavailable_text;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_enable_button = global::UnitTestFrameworkAndroid.Resource.String.common_google_play_services_enable_button;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_enable_text = global::UnitTestFrameworkAndroid.Resource.String.common_google_play_services_enable_text;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_enable_title = global::UnitTestFrameworkAndroid.Resource.String.common_google_play_services_enable_title;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_error_notification_requested_by_msg = global::UnitTestFrameworkAndroid.Resource.String.common_google_play_services_error_notification_requested_by_msg;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_install_button = global::UnitTestFrameworkAndroid.Resource.String.common_google_play_services_install_button;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_install_text_phone = global::UnitTestFrameworkAndroid.Resource.String.common_google_play_services_install_text_phone;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_install_text_tablet = global::UnitTestFrameworkAndroid.Resource.String.common_google_play_services_install_text_tablet;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_install_title = global::UnitTestFrameworkAndroid.Resource.String.common_google_play_services_install_title;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_invalid_account_text = global::UnitTestFrameworkAndroid.Resource.String.common_google_play_services_invalid_account_text;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_invalid_account_title = global::UnitTestFrameworkAndroid.Resource.String.common_google_play_services_invalid_account_title;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_needs_enabling_title = global::UnitTestFrameworkAndroid.Resource.String.common_google_play_services_needs_enabling_title;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_network_error_text = global::UnitTestFrameworkAndroid.Resource.String.common_google_play_services_network_error_text;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_network_error_title = global::UnitTestFrameworkAndroid.Resource.String.common_google_play_services_network_error_title;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_notification_needs_update_title = global::UnitTestFrameworkAndroid.Resource.String.common_google_play_services_notification_needs_update_title;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_notification_ticker = global::UnitTestFrameworkAndroid.Resource.String.common_google_play_services_notification_ticker;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_sign_in_failed_text = global::UnitTestFrameworkAndroid.Resource.String.common_google_play_services_sign_in_failed_text;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_sign_in_failed_title = global::UnitTestFrameworkAndroid.Resource.String.common_google_play_services_sign_in_failed_title;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_unknown_issue = global::UnitTestFrameworkAndroid.Resource.String.common_google_play_services_unknown_issue;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_unsupported_text = global::UnitTestFrameworkAndroid.Resource.String.common_google_play_services_unsupported_text;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_unsupported_title = global::UnitTestFrameworkAndroid.Resource.String.common_google_play_services_unsupported_title;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_update_button = global::UnitTestFrameworkAndroid.Resource.String.common_google_play_services_update_button;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_update_text = global::UnitTestFrameworkAndroid.Resource.String.common_google_play_services_update_text;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_update_title = global::UnitTestFrameworkAndroid.Resource.String.common_google_play_services_update_title;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_updating_text = global::UnitTestFrameworkAndroid.Resource.String.common_google_play_services_updating_text;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_updating_title = global::UnitTestFrameworkAndroid.Resource.String.common_google_play_services_updating_title;
			global::KinveyXamarinAndroid.Resource.String.common_open_on_phone = global::UnitTestFrameworkAndroid.Resource.String.common_open_on_phone;
			global::KinveyXamarinAndroid.Resource.String.common_signin_button_text = global::UnitTestFrameworkAndroid.Resource.String.common_signin_button_text;
			global::KinveyXamarinAndroid.Resource.String.common_signin_button_text_long = global::UnitTestFrameworkAndroid.Resource.String.common_signin_button_text_long;
			global::KinveyXamarinAndroid.Resource.String.library_name = global::UnitTestFrameworkAndroid.Resource.String.library_name;
			global::KinveyXamarinAndroid.Resource.Styleable.LoadingImageView = global::UnitTestFrameworkAndroid.Resource.Styleable.LoadingImageView;
			global::KinveyXamarinAndroid.Resource.Styleable.LoadingImageView_circleCrop = global::UnitTestFrameworkAndroid.Resource.Styleable.LoadingImageView_circleCrop;
			global::KinveyXamarinAndroid.Resource.Styleable.LoadingImageView_imageAspectRatio = global::UnitTestFrameworkAndroid.Resource.Styleable.LoadingImageView_imageAspectRatio;
			global::KinveyXamarinAndroid.Resource.Styleable.LoadingImageView_imageAspectRatioAdjust = global::UnitTestFrameworkAndroid.Resource.Styleable.LoadingImageView_imageAspectRatioAdjust;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060009
			public const int common_action_bar_splitter = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int common_signin_btn_dark_text_default = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int common_signin_btn_dark_text_disabled = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_signin_btn_dark_text_focused = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_signin_btn_dark_text_pressed = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int common_signin_btn_default_background = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int common_signin_btn_light_text_default = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int common_signin_btn_light_text_disabled = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_signin_btn_light_text_focused = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int common_signin_btn_light_text_pressed = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int common_signin_btn_text_dark = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int common_signin_btn_text_light = 2131099659;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_ic_googleplayservices = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_signin_btn_icon_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_signin_btn_icon_disabled_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_signin_btn_icon_disabled_focus_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_disabled_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_focus_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_focus_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_normal_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_normal_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_pressed_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_icon_pressed_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_text_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_text_disabled_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_text_disabled_focus_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_text_disabled_focus_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_disabled_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_focus_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_focus_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_normal_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_normal_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_pressed_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_text_pressed_light = 2130837529;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080004
			public const int OptionHostName = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int OptionPort = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int OptionRemoteServer = 2131230723;
			
			// aapt resource value: 0x7f080013
			public const int OptionsButton = 2131230739;
			
			// aapt resource value: 0x7f08000e
			public const int ResultFullName = 2131230734;
			
			// aapt resource value: 0x7f080010
			public const int ResultMessage = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int ResultResultState = 2131230735;
			
			// aapt resource value: 0x7f08000d
			public const int ResultRunSingleMethodTest = 2131230733;
			
			// aapt resource value: 0x7f080011
			public const int ResultStackTrace = 2131230737;
			
			// aapt resource value: 0x7f080009
			public const int ResultsFailed = 2131230729;
			
			// aapt resource value: 0x7f080006
			public const int ResultsId = 2131230726;
			
			// aapt resource value: 0x7f08000a
			public const int ResultsIgnored = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int ResultsInconclusive = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int ResultsMessage = 2131230732;
			
			// aapt resource value: 0x7f080008
			public const int ResultsPassed = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int ResultsResult = 2131230727;
			
			// aapt resource value: 0x7f080012
			public const int RunTestsButton = 2131230738;
			
			// aapt resource value: 0x7f080014
			public const int TestSuiteListView = 2131230740;
			
			// aapt resource value: 0x7f080000
			public const int adjust_height = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int adjust_width = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int none = 2131230722;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int options = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int results = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int test_result = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int test_suite = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050003
			public const int auth_google_play_services_client_facebook_display_name = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int auth_google_play_services_client_google_display_name = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int common_android_wear_notification_needs_update_text = 2131034118;
			
			// aapt resource value: 0x7f050013
			public const int common_android_wear_update_text = 2131034131;
			
			// aapt resource value: 0x7f050011
			public const int common_android_wear_update_title = 2131034129;
			
			// aapt resource value: 0x7f05001f
			public const int common_google_play_services_api_unavailable_text = 2131034143;
			
			// aapt resource value: 0x7f05000f
			public const int common_google_play_services_enable_button = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int common_google_play_services_enable_text = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_play_services_enable_title = 2131034125;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_error_notification_requested_by_msg = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_install_button = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_install_text_phone = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_install_text_tablet = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_install_title = 2131034121;
			
			// aapt resource value: 0x7f050019
			public const int common_google_play_services_invalid_account_text = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int common_google_play_services_invalid_account_title = 2131034136;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_needs_enabling_title = 2131034119;
			
			// aapt resource value: 0x7f050017
			public const int common_google_play_services_network_error_text = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int common_google_play_services_network_error_title = 2131034134;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_notification_needs_update_title = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int common_google_play_services_notification_ticker = 2131034116;
			
			// aapt resource value: 0x7f050021
			public const int common_google_play_services_sign_in_failed_text = 2131034145;
			
			// aapt resource value: 0x7f050020
			public const int common_google_play_services_sign_in_failed_title = 2131034144;
			
			// aapt resource value: 0x7f05001a
			public const int common_google_play_services_unknown_issue = 2131034138;
			
			// aapt resource value: 0x7f05001c
			public const int common_google_play_services_unsupported_text = 2131034140;
			
			// aapt resource value: 0x7f05001b
			public const int common_google_play_services_unsupported_title = 2131034139;
			
			// aapt resource value: 0x7f05001d
			public const int common_google_play_services_update_button = 2131034141;
			
			// aapt resource value: 0x7f050012
			public const int common_google_play_services_update_text = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int common_google_play_services_update_title = 2131034128;
			
			// aapt resource value: 0x7f050015
			public const int common_google_play_services_updating_text = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int common_google_play_services_updating_title = 2131034132;
			
			// aapt resource value: 0x7f05001e
			public const int common_open_on_phone = 2131034142;
			
			// aapt resource value: 0x7f050000
			public const int common_signin_button_text = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int common_signin_button_text_long = 2131034113;
			
			// aapt resource value: 0x7f050022
			public const int library_name = 2131034146;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
